autoconfing

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -659,9 +659,12 @@ CPPFLAGS
 ac_ct_CC
 EXEEXT
 OBJEXT
+JAVA_PATH_NAME
 CPP
 GREP
 EGREP
+JAVA_HOME
+JAVAC
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -2606,6 +2609,63 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+if test x$JAVA_HOME = x; then
+
+TRY_JAVA_HOME=`ls -dr /usr/java/* 2> /dev/null | head -n 1`
+if test x$TRY_JAVA_HOME != x; then
+	PATH=$PATH:$TRY_JAVA_HOME/bin
+fi
+# Extract the first word of "java", so it can be a program name with args.
+set dummy java; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_JAVA_PATH_NAME+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVA_PATH_NAME in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVA_PATH_NAME="$JAVA_PATH_NAME" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_JAVA_PATH_NAME="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+JAVA_PATH_NAME=$ac_cv_path_JAVA_PATH_NAME
+if test -n "$JAVA_PATH_NAME"; then
+  { echo "$as_me:$LINENO: result: $JAVA_PATH_NAME" >&5
+echo "${ECHO_T}$JAVA_PATH_NAME" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+if test x$JAVA_PATH_NAME != x; then
+	JAVA_HOME=`echo $JAVA_PATH_NAME | sed "s/\(.*\)[/]bin[/]java.*/\1/"`
+fi;
+fi
+JAVAC=$JAVA_HOME/bin/javac
+
+if test "`$JAVAC -version 2>&1 | grep '1.6'`" = ""; then
+    { { echo "$as_me:$LINENO: error: The java compiler $JAVAC does not seem to be version 1.6 (try setting JAVA_HOME)?" >&5
+echo "$as_me: error: The java compiler $JAVAC does not seem to be version 1.6 (try setting JAVA_HOME)?" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 # Checks for libraries.
 
@@ -3666,6 +3726,9 @@ done
 
 
 
+
+
+
 ac_config_files="$ac_config_files Makefile"
 
 cat >confcache <<\_ACEOF
@@ -4327,14 +4390,17 @@ CPPFLAGS!$CPPFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
+JAVA_PATH_NAME!$JAVA_PATH_NAME$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+JAVA_HOME!$JAVA_HOME$ac_delim
+JAVAC!$JAVAC$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 49; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
